In [1]:
import torch

### Checking if nvidia gpu's are available and number of devices available

In [3]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [4]:
print(torch.cuda.is_available())

False


You can count the number of GPUs PyTorch has access to using `torch.cuda.device_count()`.

### Setting Device

In [7]:
def get_device():
    if torch.cuda.is_available():
        return 'cuda'
    elif torch.backends.mps.is_available():
        return 'mps'
    else:
        return 'cpu'

device = get_device()
print(device)

mps


### Putting tensors (and models) on the GPU

In [10]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='mps:0') mps:0
tensor([1, 2, 3]) cpu


Notice the second tensor has device='mps:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'mps/cuda:0' and 'mps/cuda:1' respectively, up to 'mps/cuda:n').

In [12]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

[1 2 3] cpu
