In [1]:
import torch

# Calculating Time

In [63]:
%%time
print('a')

a
CPU times: user 53 µs, sys: 10 µs, total: 63 µs
Wall time: 59.8 µs


# Creating Tensors


### Scalar Tensors

In [15]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())
print(scalar.shape)

tensor(7)
0
7
torch.Size([])


### Vectors

In [26]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector.dtype)

tensor([7, 7])
1
torch.Size([2])
torch.int64


You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

### Matrix

In [18]:
# Matrix
matrix = torch.tensor([[7, 8], [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


matrix has two dimensions (did you count the number of square brackets on the outside of one side?).

In [32]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5.]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)

tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])
3
torch.Size([1, 3, 3])
torch.float32
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
torch.int64


Notice the tensor type changing by having 1 entry as a float

### Random Tensors

In [33]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)

tensor([[0.8270, 0.6275, 0.3518, 0.8788],
        [0.1443, 0.7010, 0.1186, 0.5628],
        [0.3699, 0.7136, 0.3363, 0.6721]])
2
torch.Size([3, 4])
torch.float32


In [34]:
random_tensor = torch.empty(size=(3, 4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])
torch.float32


### Zeros and Ones

In [41]:
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.ndim)
print(zeros.shape)
print(zeros.dtype)

print('----')

ones = torch.ones(size=(3, 4))
print(ones)
print(ones.ndim)
print(ones.shape)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])
torch.float32
----
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.Size([3, 4])
torch.float32


### Range and tensor_like

You can use torch.arange(start, end, step) to get a range

where:
start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)

In [39]:
range_tensor = torch.arange(0, 5, 2)
print(range_tensor)
print(range_tensor.ndim)
print(range_tensor.shape)
print(range_tensor.dtype)

tensor([0, 2, 4])
1
torch.Size([3])
torch.int64


In [42]:
zero_2 = torch.zeros_like(range_tensor)
print(zero_2)
print(zero_2.ndim)
print(zero_2.shape)
print(zero_2.dtype)

print('----')

ones_2 = torch.ones_like(range_tensor)
print(ones_2)
print(ones_2.ndim)
print(ones_2.shape)
print(ones_2.dtype)

tensor([0, 0, 0])
1
torch.Size([3])
torch.int64
----
tensor([1, 1, 1])
1
torch.Size([3])
torch.int64


# Data Types

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

### Float 32 tensor

In [45]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None, # defaults to None, which uses the default tensor type
    requires_grad=False # if True, operations performed on the tensor are recorded 
) 
print(float_32_tensor)
print(float_32_tensor.ndim)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

tensor([3., 6., 9.])
1
torch.Size([3])
torch.float32
cpu


# Manipulating Tensors

In [47]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([1, 2, 3])


### Adding and assignment

In [49]:
tensor = torch.tensor([1, 2, 3]) + 10
print(tensor)

tensor([11, 12, 13])


### Element-wise operation

In [52]:
print(torch.tensor([1, 2, 3]) + torch.tensor([2,4,9]))
print(torch.tensor([1, 2, 3]) * torch.tensor([2,4,9]))

tensor([ 3,  6, 12])
tensor([ 2,  8, 27])


### Matrix Multiplication

In [55]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2,4,9])

print(torch.matmul(a, b)) # (1*2 + 2*4 + 3*9)
print(a @ b)

tensor(37)
tensor(37)


Can also use the "@" symbol for matrix multiplication, though not recommende

In [58]:
a = torch.ones(size=(3,4))
b = torch.ones(size=(4,5))

c = a @ b
print(c)
print(c.shape)

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])
torch.Size([3, 5])


### Transpose of a matrix

You can perform transposes in PyTorch using either:

- torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
- tensor.T - where tensor is the desired tensor to transpose.

In [65]:
a = torch.ones(size=(3,4))
b = torch.ones(size=(4,5))

print(a.shape)
print(b.shape)

a_t = torch.transpose(a, 0, 1)
b_t = b.T

print(a_t.shape)
print(b_t.shape)

torch.Size([3, 4])
torch.Size([4, 5])
torch.Size([4, 3])
torch.Size([5, 4])


### min, max, mean, sum, etc (aggregation)

In [68]:
x = torch.arange(0, 100, 10)

In [76]:
min_x = torch.min(x)
max_x = torch.max(x)
sum_x = torch.sum(x)

print(min_x)
print(max_x)
print(sum_x)

print('------')

min_x = x.min()
max_x = x.max()
sum_x = x.sum()

print(min_x)
print(max_x)
print(sum_x)

tensor(0)
tensor(90)
tensor(450)
------
tensor(0)
tensor(90)
tensor(450)


In [73]:
mean_x = torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [77]:
mean_x = x.type(torch.float).mean()
mean_x_2 = torch.mean(x.type(torch.float))

print(mean_x)
print(mean_x_2)

print(x.dtype)

tensor(45.)
tensor(45.)
torch.int64


Notice that the input type of original 'x' didnt change

### Positional min/max

In [79]:
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


### Change tensor datatype

In [80]:
tensor = torch.arange(10., 100., 10.)
tensor_fp16 = tensor.type(torch.half)
tensor_int64 = tensor.type(torch.int64)

print(tensor.dtype)
print(tensor_fp16.dtype)
print(tensor_int64.dtype)

torch.float32
torch.float16
torch.int64


### Reshaping, stacking, squeezing and unsqueezing

In [91]:
x = torch.rand(size=(3,4))

x_reshape = torch.reshape(x, shape=(2,6))
x_reshape_2 = torch.reshape(x, shape=(4,3))
x_permute = torch.permute(x, dims=(1,0))

print(f'original_x: {x}')
print(f'reshaped_x: {x_reshape}')
print('---')

print(f'different than permuted_x: {x_reshape_2}')
print(f'permuted_x - changes info in rows to columns. useful when we want the data to mean the same stuff: {x_permute}')

original_x: tensor([[0.0766, 0.8460, 0.3624, 0.3083],
        [0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330]])
reshaped_x: tensor([[0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947, 0.0897, 0.8712, 0.1330]])
---
same as permuted_x: tensor([[0.0766, 0.8460, 0.3624],
        [0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947],
        [0.0897, 0.8712, 0.1330]])
permuted_x: tensor([[0.0766, 0.0850, 0.6947],
        [0.8460, 0.0029, 0.0897],
        [0.3624, 0.6431, 0.8712],
        [0.3083, 0.3908, 0.1330]])


In [98]:
x_unsqueeze = torch.unsqueeze(x, dim=0)
print(x)
print(x.shape)
print(x_unsqueeze)
print(x_unsqueeze.shape)

print('---')

x_unsqueeze = torch.unsqueeze(x, dim=1)
print(x)
print(x.shape)
print(x_unsqueeze)
print(x_unsqueeze.shape)

tensor([[0.0766, 0.8460, 0.3624, 0.3083],
        [0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330]])
torch.Size([3, 4])
tensor([[[0.0766, 0.8460, 0.3624, 0.3083],
         [0.0850, 0.0029, 0.6431, 0.3908],
         [0.6947, 0.0897, 0.8712, 0.1330]]])
torch.Size([1, 3, 4])
---
tensor([[0.0766, 0.8460, 0.3624, 0.3083],
        [0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330]])
torch.Size([3, 4])
tensor([[[0.0766, 0.8460, 0.3624, 0.3083]],

        [[0.0850, 0.0029, 0.6431, 0.3908]],

        [[0.6947, 0.0897, 0.8712, 0.1330]]])
torch.Size([3, 1, 4])


In [102]:
x_squeeze = torch.squeeze(x_unsqueeze, dim=1)
print(x_unsqueeze)
print(x_unsqueeze.shape)
print(x_squeeze)
print(x_squeeze.shape)

tensor([[[0.0766, 0.8460, 0.3624, 0.3083]],

        [[0.0850, 0.0029, 0.6431, 0.3908]],

        [[0.6947, 0.0897, 0.8712, 0.1330]]])
torch.Size([3, 1, 4])
tensor([[0.0766, 0.8460, 0.3624, 0.3083],
        [0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330]])
torch.Size([3, 4])


### Views

In [108]:
x = torch.tensor([[2,6], [1,3]])
tensor_view = x.view((1,4))

print(x)
print(tensor_view)

tensor([[2, 6],
        [1, 3]])
tensor([[2, 6, 1, 3]])


#### Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

### Indexing

In [111]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [113]:
# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(x[0, 0, :]) # same as x[0][0]


tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


# PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

- torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
- torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [114]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [115]:
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Randomness

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness. So you can perform repeatable experiments. 
That's where `torch.manual_seed(seed)` comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

In [118]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Linear Layer multiplication

In [66]:
torch.manual_seed(42)

x = torch.rand(size=(3,2))
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[-0.2539,  0.2555,  0.3376,  0.4656, -0.0777,  1.0456],
        [-0.0635, -0.0787,  0.0365,  0.2090, -0.2524,  0.7780],
        [-0.2150,  0.1119, -0.0063,  0.1786, -0.2141,  0.7447]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


output shape = (3*2) * (2*6) = (3*6)